### PR TITLE
added SideBar status effect, removed EPOP-message

### PR DESCRIPTION
**Pull request by BeeJay28**
I removed the EPOP-notification and added a sidebar-status effect from TTT2 as replacement (debatable to keep both). It uses the [sidebar-API from TTT2](https://docs.ttt2.neoxult.de/developers/content-creation/sidebar-population/) and thus includes a little timer and is uniform with the default UI design.
Some clarity is traded away, since it is not immediately obvious that _everyone_ is immune instead of just the player themselves. Additional clarity through some form of Doc or Readme file might be appropriate.

### CODE REVIEW

**Comment by ZenBre4ker** [comment]
You are right, thats a sick addition, definitely better than the message. Will take a look at it 🔥

**Comment by ZenBre4ker** [comment]
I got this error:
```
[ttt2] addons/ttt2/gamemodes/terrortown/gamemode/server/sv_status.lua:51: bad argument #1 to 'WriteUInt' (number expected, got boolean)  
1. WriteUInt - [C]:-1
   2. AddTimedStatus - addons/ttt2/gamemodes/terrortown/gamemode/server/sv_status.lua:51
    3. fn - addons/ttt2_ceasefire/lua/terrortown/autorun/shared/sh_ceasefire.lua:23
     4. Run - lua/ulib/shared/hook.lua:109
      5. unknown - addons/ttt2/gamemodes/terrortown/gamemode/server/sv_main.lua:1223
```

I think 3s for beginners is not enough, its also just a default.
But I really like the status icon. 

Going to change them myself now, as I have time right now :D

**Comment by ZenBre4ker** [comment]
Oops when you dont know your own code, 3s is minimal not default duration..... changed it back to 3 again

**Comment by ZenBre4ker** [comment]
And added the Epop message to clarify.

**Comment by BeeJay28** [comment]
Sweet. Sorry, I kinda forgot about this PR x). Yea, I changed to minimum to 3 secs, mostly due to personal preference. I didn't think there would be a problem with that. What a fool I was 😅.
Anyway, my friends like to play with the Minigame-Addon, which ocassionally announces randomized minigames through EPOP-messages and it is often delayed because of the Ceasefire message. Perhaps it would be possible to add another ConVar to regulate whether the EPOP appears or not (the sidebar doesn't have that problem, so no need for ConVars there).

**Pull request merged**
